import type { Metadata } from "next";
import "./globals.css";
// Slick carousel styles (react-slick)
// Removed slick-carousel CSS imports because the package is not installed.
// If a carousel is needed later, install `slick-carousel` and `react-slick`, then re-add:
// import "slick-carousel/slick/slick.css";
// import "slick-carousel/slick/slick-theme.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
  <body className={`antialiased`}>
        {children}
      </body>
    </html>
  );
}
